// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace wr.entity
{
    public partial class Product
    {
        public int Pid { get; set; }
        public string Name { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public DateTime? WarentyEndDate { get; set; }
        public string ImageLink { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? CreatedBy { get; set; }
        public bool? IsActive { get; set; }
    }
}